sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 925828
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6NHiwrHz7myGMLxY6L
    access-key-secret: e8tEqI2hpGlExUUr5y0NcOnzZdAj9N
    bucket-name: skytakeout-aliyunoss
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx5d7a55c82eb476fb
    secret: 705e12f875938fdfacb4e51ec1ffaa34