sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 925828
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6NHiwrHz7myGMLxY6L
    access-key-secret: e8tEqI2hpGlExUUr5y0NcOnzZdAj9N
    bucket-name: skytakeout-aliyunoss
